CREATE TABLE STUDENT (
  ID INT PRIMARY KEY,
  FIRST_NAME VARCHAR (20),
  LAST_NAME VARCHAR (20),
  SEX CHAR CHECK (SEX IN ('M', 'F', 'O')),
  DOB DATE,
  ADDRESS VARCHAR (60),
  CITY VARCHAR (10),
  STATE VARCHAR (15),
  PIN_CODE INT,
  PHONE BIGINT,
  MARKS_O INT,
  MARKS_T INT
);
